### ISSUE TITLE
Tackling Redundancy in Multi Topic Selection

### ISSUE THREAD

**Issue by JamieHorsnell** [dickreuter/sparkai-chatbot-frontend#16]
Have the responses for the multi-topic function work so that it doesn't bring up two similar responses. 

For some of the multi-topic selection function response, each sub-heading includes the same contents from the database and pretty similar responses.

My attempts in prompting 3b to not include haven't been successful so far. Prompting 3a to generate sub-topics that are separate slightly improves this, but still occurs. 

A couple of example questions if that helps you prompt engineering:
- Please outline your management structure applicable to this contract and how potential issues encountered in delivering the requirements are managed and reported. Provide details of the knowledge, skills and experience within your team who are key to this contract.
- Contract 1: Contract details and a brief description of the contract delivered including evidence as to your technical capability in this market.

**Comment by dickreuter** [comment]
Have you tried to explain in the 3b prompt that the response will be part of a larger task and that there should be some additional randomness in how the text starts, to avoid duplication? Or possibly to avoid an intro,  but only focus on this very topic.

**Comment by JamieHorsnell** [comment]
I tried quite a few prompts, this being one of them and some a bit more direct: 

Focus your answer on the following sub topic, however this answer will be part of a longer answer, so do not include introductions or conclusions at the end of your responses. Please generate each sub-topic 300-400 words: {sub_topic}

**Comment by dickreuter** [comment]
I would suggest to specifically tell it to add randomness in the initial part, so that there will be less overlap on anything that is not very specific to the topic. 

To this specific issue, the solution will almost certainly have to come through prompting in some way, as it's currently not possible to have the LLM output such a long text with a single query. Maybe this will change in the near future.
