### ISSUE TITLE
Co-Pilot Function

### ISSUE THREAD

**Issue by JamieHorsnell** [dickreuter/sparkai-chatbot-frontend#17]
Have as an editing tool rather than a continuing answer tool.

Be able to highlight a section of the response, and then type in instructions for how you would like the text modified i.e expanded, simplified, or more detail about xyz.

I think it would be good if the highlighted section got instantly replaced by the co-pilot edit back into the response.

**Comment by dickreuter** [comment]
Copilot now asks for instructions
