### ISSUE TITLE
Redesign login page

### ISSUE THREAD

**Issue by JamieHorsnell** [dickreuter/sparkai-chatbot-frontend#23]
a) Reposition the login form.

b) Add a logo(svg).

c) Activate the password recovery function. [this is mainly a backend change]

Page 1 of - [UI (3).pdf](https://github.com/dickreuter/sparkai-chatbot-frontend/files/14191485/UI.3.pdf)

**Comment by Samuel-Aaron1** [comment]
<img width="886" alt="image" src="https://github.com/dickreuter/sparkai-chatbot-frontend/assets/159250556/4bd4c867-eb0b-4d87-82f9-db2337416d17">
