### ISSUE TITLE
Intermediary step to store question/answer pairs separately before sending it to the editor

### ISSUE THREAD

**Issue by dickreuter** [dickreuter/sparkai-chatbot-frontend#24]
Frontend change:
Currently, the "add response to text editor' button moves the answer to the editor. There should be an intermediary step first:

Move the question/answer pair to an intermediary view. From there it can then be selected (probably via tickbox) to move to the editor for final editing. In the editor, we'll want to see both the question and the answer.

**Comment by Samuel-Aaron1** [comment]
<img width="660" alt="image" src="https://github.com/dickreuter/sparkai-chatbot-frontend/assets/159250556/370e2cda-8649-4d0c-ac4a-29920210074d">

**Comment by JamieHorsnell** [comment]
Updated Version: 

[Proposal Editor Page.pdf](https://github.com/dickreuter/sparkai-chatbot-frontend/files/14196789/Proposal.Editor.Page.pdf)
