### ISSUE TITLE
Company Library

### ISSUE THREAD

**Issue by Samuel-Aaron1** [dickreuter/sparkai-chatbot-frontend#28]
- Initial Page after logging in where the user can view and interact with their uploaded data. Eg pdf's, images and Word documents. Which will detail previous bids, case studies, company policies etc. 
The user can start a new bid from here through a button on the chatbot page
- User can view completed bids which have been previously submitted on the system

**Comment by Samuel-Aaron1** [comment]
<img width="928" alt="image" src="https://github.com/dickreuter/sparkai-chatbot-frontend/assets/159250556/5032d9ee-72a8-4dfc-b3c4-faf6c6355209">

**Comment by JamieHorsnell** [comment]
<img width="503" alt="Screenshot 2024-02-07 090623" src="https://github.com/dickreuter/sparkai-chatbot-frontend/assets/146178239/a4bdec85-1815-4fbd-b9dc-950cbdc789b9">

Hyperlink to each bid where the information is saved on the bid name.

A dropdown on the status of the bids: Upcoming, Ongoing and Finished.
