### ISSUE TITLE
PDF and Text Uploader Front End Improvement

### ISSUE THREAD

**Issue by JamieHorsnell** [dickreuter/sparkai-chatbot-frontend#56]
- Whatever you think would look good Alex
- Remove the text format button on the text uploader page (pointless button)
- Change ‘Profile name’ to ‘folder’
- Change text inside the text upload box to ‘Paste bid material here’ (No need for all the current writing)

**Comment by dickreuter** [comment]
The uploaded page now has quite a lot of items. Would it possibly make sense to have a vertical menu bar as well?

**Comment by okk0** [comment]
resolved
