### ISSUE TITLE
Confirm Data Upload Pop-up

### ISSUE THREAD

**Issue by JamieHorsnell** [dickreuter/sparkai-chatbot-frontend#57]
Once you drag a PDF into the drop zone, or click on the ‘upload data’ button, a pop-up will display in the middle of the screen ‘Are you sure you want to upload this document’ to the text and PDF uploader.

When the pop-up comes up the rest of the screen goes darker until either ‘cancel’ or ‘upload data’ button has been pressed.

Something similar to this but just says ‘Upload Data’ and ‘Are you sure you want to update this workflow’ with ‘Upload’ instead of delete.

The colour for the ‘Upload’ button can be #F7AE36 or #F29131 (Or something near that, whatever you think looks best). Can this also match the colour of the functionality box on the response generator page.
<img width="231" alt="image" src="https://github.com/dickreuter/sparkai-chatbot-frontend/assets/146178239/2b095660-986e-4c0e-abe3-7f1675d25452">

**Comment by okk0** [comment]
resolved
