### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by JamieHorsnell** [dickreuter/sparkai-chatbot-frontend#6]
<img width="740" alt="Status code ss" src="https://github.com/dickreuter/sparkai-chatbot-frontend/assets/146178239/cebac9fd-c439-4351-b350-9f7d15001ef3">

Response coming up with 'Request failed with status code 400'

**Comment by dickreuter** [comment]
Is this only for one user? If so, which one? Can you give me login and password so I can reproduce it?

**Comment by dickreuter** [comment]
fixed
